### ISSUE TITLE
Prefix Error Not Right

### ISSUE THREAD

**Issue by redreceipt** [deepakputhraya/action-pr-title#14]
It's saying my prefix isn't correct but it is, not sure how to debug or fix it from here

<img width="954" alt="Screen Shot 2020-12-09 at 9 10 21 PM" src="https://user-images.githubusercontent.com/2659478/101712231-0f6e6b00-3a63-11eb-8541-d3b19d214877.png">

**Comment by deepakputhraya** [comment]
Please use `,` and not `, `. We do not trim space as we want to support space as a valid prefix.
