### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SapeginRenat** [deepakputhraya/action-pr-title#3]
![Screenshot from 2020-02-18 11-22-06](https://user-images.githubusercontent.com/23656255/74722044-f204b200-5240-11ea-8b92-ec7c5389dde5.png)

![Screenshot from 2020-02-18 11-19-55](https://user-images.githubusercontent.com/23656255/74721941-cda8d580-5240-11ea-85cd-94285fcd7e87.png)
`

**Comment by asyazwan** [comment]
The default regex is expecting `/` separator, not `-`.
If you want `-` change the regex to `([a-z])+-([a-z])+`.
