### ISSUE TITLE
re-run the action after renaming the PR title does not work

### ISSUE THREAD

**Issue by tbarbugli** [deepakputhraya/action-pr-title#4]
- Create a PR with bad title
- Github Action fails
- Rename PR with good title
- Re-run Github action
- Github action fails again on the previous PR title

Only solution I found is to close/open a new PR or kick the build via commit; both are not great.

**Comment by deepakputhraya** [comment]
@tbarbugli I have made the changes. The action will always use the latest PR title in the checks. Please refer to the Readme for further details.
